#!/usr/bin/env sh
set -eu

DOMAIN="${1:-api.gtaelectricservices.ca}"
EMAIL="${2:-}"

if [ -z "$EMAIL" ]; then
  echo "Usage: $0 <domain> <letsencrypt-email>"
  echo "Example: $0 api.gtaelectricservices.ca admin@gtaelectricservices.ca"
  exit 1
fi

SCRIPT_DIR="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)"
DROPLET_DIR="$(CDPATH= cd -- "$SCRIPT_DIR/.." && pwd)"

cd "$DROPLET_DIR"

write_http_bootstrap() {
  cat > "$DROPLET_DIR/nginx/conf.d/gtaes.conf" <<EOF
# Initial HTTP-only config (before SSL). Replaced after cert issuance.

upstream gtaes_api {
    server api:3001;
    keepalive 32;
}

server {
    listen 80;
    listen [::]:80;
    server_name $DOMAIN;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        proxy_pass http://gtaes_api;
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_set_header Connection "";
        proxy_read_timeout 120s;
    }
}
EOF
}

write_https_config() {
  # Write HTTPS config inline so an outdated template cannot keep an old domain
  # like gtaes.nicheye.com after a successful cert for $DOMAIN.
  cat > "$DROPLET_DIR/nginx/conf.d/gtaes.conf" <<EOF
# HTTPS config generated by scripts/init-ssl.sh for $DOMAIN

upstream gtaes_api {
    server api:3001;
    keepalive 32;
}

server {
    listen 80;
    listen [::]:80;
    server_name $DOMAIN;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://\$host\$request_uri;
    }
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    http2 on;
    server_name $DOMAIN;

    ssl_certificate /etc/letsencrypt/live/$DOMAIN/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/$DOMAIN/privkey.pem;
    ssl_session_timeout 1d;
    ssl_session_cache shared:SSL:10m;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers off;

    add_header Strict-Transport-Security "max-age=63072000; includeSubDomains" always;

    location / {
        proxy_pass http://gtaes_api;
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_set_header Connection "";
        proxy_read_timeout 120s;
        proxy_send_timeout 120s;
    }
}
EOF

  if grep -q 'nicheye.com\|__DOMAIN__' "$DROPLET_DIR/nginx/conf.d/gtaes.conf"; then
    echo "ERROR: nginx config still contains an unexpected domain placeholder." >&2
    exit 1
  fi
}

echo "==> Writing HTTP bootstrap nginx config for $DOMAIN..."
write_http_bootstrap

echo "==> Ensuring stack is running (HTTP bootstrap config)..."
docker compose up -d db api nginx
docker compose exec nginx nginx -t
docker compose exec nginx nginx -s reload

echo "==> Requesting Let's Encrypt certificate for $DOMAIN..."
docker compose run --rm --entrypoint certbot certbot certonly \
  --webroot \
  --webroot-path=/var/www/certbot \
  --email "$EMAIL" \
  --agree-tos \
  --no-eff-email \
  -d "$DOMAIN"

echo "==> Enabling HTTPS nginx config for $DOMAIN..."
write_https_config

echo "==> Reloading nginx..."
docker compose exec nginx nginx -t
docker compose exec nginx nginx -s reload

echo "==> Starting certbot renewal loop..."
docker compose --profile ssl up -d certbot

echo ""
echo "Done. API should be available at https://$DOMAIN/health"
echo ""
echo "Set Vercel env vars:"
echo "  Admin: VITE_API_URL=https://$DOMAIN"
echo "  Admin: VITE_WEB_URL=https://gtaelectricservices.ca"
echo "  Web:   NEXT_PUBLIC_API_URL=https://$DOMAIN"
echo ""
echo "Droplet .env CORS_ORIGINS should include:"
echo "  https://admin.gtaelectricservices.ca,https://gtaelectricservices.ca,https://www.gtaelectricservices.ca,"
echo "  https://admin-gtaes-git-main-gtaes.vercel.app,https://web-gtaes-git-main-gtaes.vercel.app"
